SELECT 
    R.CAR_ID,
    R.CAR_TYPE,
    FLOOR(R.DAILY_FEE * (100 - P.DISCOUNT_RATE) / 100 * 30) AS FEE
FROM CAR_RENTAL_COMPANY_CAR R
LEFT JOIN CAR_RENTAL_COMPANY_RENTAL_HISTORY H
    ON R.CAR_ID = H.CAR_ID
    AND H.START_DATE <= '2022-11-30'
    AND H.END_DATE >= '2022-11-01'
JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN P
    ON R.CAR_TYPE = P.CAR_TYPE
WHERE H.CAR_ID IS NULL
  AND R.CAR_TYPE IN ('세단', 'SUV')
  AND P.DURATION_TYPE = '30일 이상'
  AND FLOOR(R.DAILY_FEE * (100 - P.DISCOUNT_RATE) / 100 * 30) BETWEEN 500000 AND 1999999
ORDER BY FEE DESC, R.CAR_TYPE ASC, R.CAR_ID DESC;