WITH RECURSIVE recur AS (
  SELECT
    ID,
    PARENT_ID,
    1 AS GENERATION
  FROM ECOLI_DATA
  WHERE PARENT_ID IS NULL

  UNION ALL

  SELECT
    e.ID,
    e.PARENT_ID,
    recur.GENERATION + 1 AS GENERATION
  FROM recur
  JOIN ECOLI_DATA e
    ON e.PARENT_ID = recur.ID
)
SELECT
  COUNT(*) AS COUNT,
  GENERATION
FROM recur
WHERE ID NOT IN (
  SELECT DISTINCT PARENT_ID
  FROM ECOLI_DATA
  WHERE PARENT_ID IS NOT NULL
)
GROUP BY GENERATION
ORDER BY GENERATION;
